name: Bugg OS Release Build

on: workflow_dispatch

jobs:
    image-builder:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up SSH debug console
                if: false   # set to true to enable debugging over SSH
                uses: mxschmitt/action-tmate@v3
                with:
                    detached: true

            -   name: Checkout Bugg OS 
                uses: actions/checkout@v4

            -   name: Checkout pi-gen
                uses: actions/checkout@v4
                with:
                    repository: RPi-Distro/pi-gen
                    ref: 2024-03-12-raspios-bookworm-arm64
                    #ref: arm64
                    path: pi-gen

            -   name: Checkout Bugg Soundcard Driver
                uses: actions/checkout@v4
                with:
                    repository: jeffmakes/bugg-soundcard-driver
                    path: stage-bugg-os/files/bugg-soundcard-driver

            -   name: Install Dependencies for the pi-gen build
                run: |
                    sudo apt-get update
                    sudo apt-get install -y \
                    coreutils \
                    quilt \
                    parted \
                    qemu-user-static \
                    debootstrap \
                    zerofree \
                    zip \
                    dosfstools \
                    libarchive-tools \
                    libcap2-bin \
                    grep \
                    rsync \
                    xz-utils \
                    file \
                    git \
                    curl \
                    bc \
                    qemu-utils \
                    kpartx \
                    gpg \
                    pigz \
                    xxd \
                    kmod \
                    python3-dev \
                    device-tree-compiler \

            -   name: Build Bugg OS
                run: |
                    echo "RELEASE_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
                    echo "IMG_FILENAME=$RELEASE_VERSION" >> config
                    echo "ARCHIVE_FILENAME=$RELEASE_VERSION" >> config
                    echo "IMG_SUFFIX=\"\"" >> config
                    sed "s/VERSION/$RELEASE_VERSION/g" stage-bugg-os/00-configure-bugg-os/issue_template > stage-bugg-os/00-configure-bugg-os/issue
                    touch pi-gen/stage3/SKIP
                    touch pi-gen/stage4/SKIP
                    touch pi-gen/stage5/SKIP
                    touch pi-gen/stage4/SKIP_IMAGES
                    touch pi-gen/stage5/SKIP_IMAGES
                    cp config pi-gen/config
                    cp -R stage-bugg-os pi-gen
                    cd pi-gen
                    sudo ./build.sh

            -   name: Debug Environment Variables
                run: |
                    echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}"
                    echo "Workspace Path=${{ github.workspace }}"
                    echo "Full Path=${{ github.workspace }}/pi-gen/deploy/${{ env.RELEASE_VERSION }}-lite.img.gz"
                   
            -   name: List artifacts
                uses: actions/github-script@v5
                with:
                    script: |
                        with:
                            script: |
                            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                                owner: context.repo.owner,
                                repo: context.repo.repo,
                                run_id: context.runId
                            });
                        console.log(artifacts.data);

            -   name: Verify Image Exists
                run: |
                        if [ -f "${{ github.workspace }}/pi-gen/deploy/${{ env.RELEASE_VERSION }}-lite.img.gz" ]; then
                            echo "File exists and will be uploaded."
                        else
                            echo "File does not exist, check previous steps."
                            exit 1
                        fi
                      

            -   name: Upload Bugg OS image
                if: ${{ github.actions }}
                uses: actions/upload-artifact@v3
                with:
                    name: ${{ env.RELEASE_VERSION }}
                    path: ${{ github.workspace }}/pi-gen/deploy/${{ env.RELEASE_VERSION }}-lite.img.gz
