name: Bugg OS Release Build

env:
    PLATFORM: bookworm

on: workflow_dispatch

jobs:
    image-builder:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Bugg OS 
                uses: actions/checkout@v4

            -   name: Checkout pi-gen
                uses: actions/checkout@v4
                with:
                    repository: RPi-Distro/pi-gen
                    ref: arm64
                    path: pi-gen
                    
            -   name: Install Dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install -y \
                    coreutils \
                    quilt \
                    parted \
                    qemu-user-static \
                    debootstrap \
                    zerofree \
                    zip \
                    dosfstools \
                    libarchive-tools \
                    libcap2-bin \
                    grep \
                    rsync \
                    xz-utils \
                    file \
                    git \
                    curl \
                    bc \
                    qemu-utils \
                    kpartx \
                    gpg \
                    pigz \

