name: Bugg OS Release Build

on: workflow_dispatch

jobs:
    image-builder:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up SSH debug console
                if: false   # set to true to enable debugging over SSH
                uses: mxschmitt/action-tmate@v3
                with:
                    detached: true

            -   name: Checkout Bugg OS 
                uses: actions/checkout@v4

            -   name: Checkout pi-gen
                uses: actions/checkout@v4
                with:
                    repository: RPi-Distro/pi-gen
                    ref: 2024-03-12-raspios-bookworm-arm64
                    #ref: arm64
                    path: pi-gen

            -   name: Checkout Bugg Soundcard Driver
                uses: actions/checkout@v4
                with:
                    repository: jeffmakes/bugg-soundcard-driver
                    path: stage-bugg-os/files/bugg-soundcard-driver

            -   name: Install Dependencies for the pi-gen build
                run: |
                    sudo apt-get update
                    sudo apt-get install -y \
                    coreutils \
                    quilt \
                    parted \
                    qemu-user-static \
                    debootstrap \
                    zerofree \
                    zip \
                    dosfstools \
                    libarchive-tools \
                    libcap2-bin \
                    grep \
                    rsync \
                    xz-utils \
                    file \
                    git \
                    curl \
                    bc \
                    qemu-utils \
                    kpartx \
                    gpg \
                    pigz \
                    xxd \
                    kmod \
                    python3-dev \
                    device-tree-compiler \

            # -   name: Set release version
            #     run: |
            #         export VERSION=$(git describe --tags --always)
            #         echo "IMG_FILENAME=$VERSION" > pi-gen/config
            #         echo "ARCHIVE_FILENAME=$VERSION" > pi-gen/config
            #         echo "IMG_SUFFIX=\"\"" >> pi-gen/config

            -   name: Build Bugg OS
                run: |
                    export IMG_FILENAME="Adze-0.1.0-alpha"
                    export ARCHIVE_FILENAME="Adze-0.1.0-alpha"
                    export IMG_SUFFIX=""
                    touch pi-gen/stage3/SKIP
                    touch pi-gen/stage4/SKIP
                    touch pi-gen/stage5/SKIP
                    touch pi-gen/stage4/SKIP_IMAGES
                    touch pi-gen/stage5/SKIP_IMAGES
                    cp config pi-gen/config
                    cp -R stage-bugg-os pi-gen
                    cd pi-gen
                    sudo ./build.sh

            # -   name: Upload Bugg OS image
            #     if: true
            #     uses: actions/upload-artifact@v3
            #     with:
            #         name: BuggOS
            #         path: pi-gen/deploy/*BuggOS*
