name: Bugg OS Release Build

on: workflow_dispatch

jobs:
    image-builder:
        runs-on: ubuntu-latest
        steps:
            -   name: Cache pi-gen work directory
                if: false
                uses: actions/cache@v3
                with:
                    path: pi-gen/work
                    key: ${{ runner.os }}-pi-gen

            -   uses: actions/checkout@v4
            -   name: Set up SSH debug console
                if: true   # set to true to enable debugging over SSH
                uses: mxschmitt/action-tmate@v3
                with:
                    detached: true

            -   name: Checkout Bugg OS 
                uses: actions/checkout@v4

            -   name: Checkout pi-gen
                uses: actions/checkout@v4
                with:
                    repository: RPi-Distro/pi-gen
                    ref: arm64
                    path: pi-gen

            -   name: Checkout Bugg Userspace Recording Firmware
                uses: actions/checkout@v4
                with:
                    repository: jeffmakes/bugg-cm4-firmware
                    path: bugg-cm4-firmware
                
            -   name: Copy Bugg Userspace Recording Firmware into staging folder
                run: |
                    mkdir stage-bugg-os/00-configure-bugg-os/files
                    cp -R bugg-cm4-firmware stage-bugg-os/00-configure-bugg-os/files
                    
            -   name: Install Dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install -y \
                    coreutils \
                    quilt \
                    parted \
                    qemu-user-static \
                    debootstrap \
                    zerofree \
                    zip \
                    dosfstools \
                    libarchive-tools \
                    libcap2-bin \
                    grep \
                    rsync \
                    xz-utils \
                    file \
                    git \
                    curl \
                    bc \
                    qemu-utils \
                    kpartx \
                    gpg \
                    pigz \

            -   name: print
                run: |
                    ls pi-gen

            -   name: Build Bugg OS
                run: |
                    touch pi-gen/stage3/SKIP
                    touch pi-gen/stage4/SKIP
                    touch pi-gen/stage5/SKIP
                    touch pi-gen/stage4/SKIP_IMAGES
                    touch pi-gen/stage5/SKIP_IMAGES
                    cp config pi-gen/config
                    cp -R stage-bugg-os pi-gen
                    cd pi-gen
                    sudo ./build.sh

            -   name: Make pi-gen work folder readable to cache process
                run: |
                    sudo rm -rf pi-gen/work/BuggOS/stage0/rootfs/dev
                    sudo rm -rf pi-gen/work/BuggOS/stage1/rootfs/dev
                    sudo rm -rf pi-gen/work/BuggOS/stage2/rootfs/dev
                    sudo rm -rf pi-gen/work/BuggOS/stage3/rootfs/dev
                    sudo rm -rf pi-gen/work/BuggOS/stage4/rootfs/dev
                    sudo rm -rf pi-gen/work/BuggOS/stage5/rootfs/dev
                    sudo chmod --recursive a+rX pi-gen/work

            -   name: Print deploy
                run: |
                    tree pi-gen/deploy

            -   name: Upload Bugg OS image
                uses: actions/upload-artifact@v3
                with:
                    name: BuggOS
                    path: pi-gen/deploy/*BuggOS*